title: Site

pages: 
  template:
    - default
    - projects
    - blog

fields:
  title:
    label: Title
    type:  text

  author:
    label: Author
    type:  text

  description:
    label: Description
    type:  textarea
